# Generated by Django 5.0.7 on 2024-07-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_alter_post_broadcasted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme_sansserif',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme_zialucia',
        ),
    ]
