# Generated by Django 5.0.7 on 2024-07-21 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0104_remove_user_theme_sansserif_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="comments_on",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
