# Generated by Django 5.0.7 on 2024-07-22 22:52

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0105_remove_user_comments_on_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                help_text="To setup: Add an A record in your domain's DNS with IP 91.107.232.152",
                max_length=150,
                null=True,
                validators=[main.validators.validate_domain_name],
            ),
        ),
    ]
