# Generated by Django 5.0.7 on 2024-07-25 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0107_remove_user_monero_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Onboard",
        ),
    ]
