# Generated by Django 5.0.7 on 2024-07-25 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0108_delete_onboard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_subscription_id",
        ),
    ]
