# Generated by Django 5.0.7 on 2024-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0109_remove_user_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="footer_note",
            field=models.TextField(
                blank=True,
                default="Powered by [capivaras.dev](https://capivaras.dev/).",
                help_text="Supports markdown",
                null=True,
            ),
        ),
    ]
