# Generated by Django 5.2.3 on 2025-07-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_alter_user_footer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='markdown_link_paste_on',
            field=models.BooleanField(default=False, help_text='Enable/disable automatic markdown link formatting on paste.', verbose_name='Markdown link formatting'),
        ),
    ]
