# Generated by Django 5.2.4 on 2025-09-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_user_markdown_link_paste_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications_on',
            field=models.BooleanField(default=False, help_text='Allow/disallow people subscribing for email newsletter for new posts.', verbose_name='Newsletter'),
        ),
    ]
