# Generated by Django 5.2.4 on 2025-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_alter_user_notifications_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticpage',
            name='referer',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='analyticpost',
            name='referer',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
