# Generated by Django 5.2.4 on 2025-09-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_analyticpage_referer_analyticpost_referer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticpage',
            name='referer',
        ),
        migrations.RemoveField(
            model_name='analyticpost',
            name='referer',
        ),
    ]
