# Generated by Django 6.0 on 2025-12-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_remove_analyticpage_referer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post_backups_on',
        ),
        migrations.DeleteModel(
            name='Snapshot',
        ),
    ]
