name: Django Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install Dependencies
      run: |
        uv sync --locked
    - name: Run Tests
      run: |
        uv run manage.py collectstatic --noinput
        DEBUG=1 uv run manage.py test
      env:
        SECRET_KEY: 'thisisthesecretkey'
        DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/postgres'
    - name: Lint
      run: |
        touch .envrc
        uv run ruff check .
